package com.blackboxstudios.rafael.reclutamento_android.utils;

/**
 * Created by Rafael on 30/09/2015.
 */
public class Constants {
    /**
     * The headers that need to be included in every request to the API
     */

    public static String content_type = "Content-Type/json";
    public static String apiKey = "trakt-api-key";
    public static String apiVersion = "trakt-api-version";

    /**
     * Url to get info for the chosen series, in this case The Walking Dead Season 5
     */

    public static String episodesUrl = "https://api-v2launch.trakt.tv/shows/the-walking-dead/seasons/5";
    public static String ratingsUrl = "https://api-v2launch.trakt.tv/shows/the-walking-dead/ratings";

    /**
     * The values of our app, the API key correspond to the one we generated by registering to trakt
     */

    public static String content_typeValue = "application/json";
    public static String apiKeyValue = "1fc602693bfd56a7232d53df7bdab5f9824467de687a969998dd4dbeabdae831";
    public static String apiVersionValue = "2";

    /**
     * Images Urls
     */

    public static String thumbnailImage = "https://walter.trakt.us/images/shows/000/001/393/fanarts/original/fc68b3b649.jpg";
    public static String coverImage = "https://walter.trakt.us/images/shows/000/001/393/posters/thumb/de0ca49881.jpg";
}
